import './css/style.css'

import { Inter } from 'next/font/google'
import Theme from './theme-provider'
import AppProvider from './app-provider'
import { AuthProvider } from '@/components/auth/auth-provider'
import { CartProvider } from '@/contexts/cart-context'
import { WishlistProvider } from '@/contexts/wishlist-context'
import { NotificationProvider } from '@/contexts/notification-context'
import { NotificationToastContainer } from '@/components/notification-toast'
import { AIChatbotProvider } from '@/components/ai-chatbot-provider'
import { LayoutProvider } from '@/contexts/LayoutContext'
import { ChatProvider } from '@/contexts/chat-context'
import { ResizableLayout } from '@/components/resizable-layout'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
  fallback: ['system-ui', 'arial'],
  preload: false, // Disable preloading to avoid network issues during build
})

export const metadata = {
  title: 'Outreach Mosaic',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable} global-no-scrollbar`} suppressHydrationWarning>{/* suppressHydrationWarning: https://github.com/vercel/next.js/issues/44343 */}
      <body className="font-inter antialiased">
        <Theme>
          <AuthProvider>
            <AppProvider>
              <CartProvider>
                <WishlistProvider>
                  <NotificationProvider>
                    <AIChatbotProvider>
                      <ChatProvider>
                        <LayoutProvider>
                          <ResizableLayout>
                            {children}
                          </ResizableLayout>
                          <NotificationToastContainer />
                        </LayoutProvider>
                      </ChatProvider>
                    </AIChatbotProvider>
                  </NotificationProvider>
                </WishlistProvider>
              </CartProvider>
            </AppProvider>
          </AuthProvider>
        </Theme>
      </body>
    </html>
  )
}
