import './css/style.css'

import { Inter } from 'next/font/google'
import Theme from './theme-provider'
import AppProvider from './app-provider'
import { AuthProvider } from '@/components/auth/auth-provider'
import { CartProvider } from '@/contexts/cart-context'
import { WishlistProvider } from '@/contexts/wishlist-context'
import { NotificationProvider } from '@/contexts/notification-context'
import { NotificationToastContainer } from '@/components/notification-toast'
import { AIChatbotProvider } from '@/components/ai-chatbot-provider'
import { LayoutProvider } from '@/contexts/LayoutContext'
import { UserContextProvider } from '@/components/user-context-provider'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata = {
  title: 'Outreach Mosaic',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable}`} suppressHydrationWarning>{/* suppressHydrationWarning: https://github.com/vercel/next.js/issues/44343 */}
      <body className="font-inter antialiased bg-gray-100 dark:bg-gray-900 text-gray-600 dark:text-gray-400">
        <Theme>
          <AuthProvider>
            <UserContextProvider>
              <AppProvider>
                <CartProvider>
                  <WishlistProvider>
                    <NotificationProvider>
                      <AIChatbotProvider>
                        <LayoutProvider>
                          {children}
                          <NotificationToastContainer />
                        </LayoutProvider>
                      </AIChatbotProvider>
                    </NotificationProvider>
                  </WishlistProvider>
                </CartProvider>
              </AppProvider>
            </UserContextProvider>
          </AuthProvider>
        </Theme>
      </body>
    </html>
  )
}
