import './css/style.css'

import { Inter } from 'next/font/google'
import Theme from './theme-provider'
import AppProvider from './app-provider'
import { AuthProvider } from '@/components/auth/auth-provider'
import { CartProvider } from '@/contexts/cart-context'
import { NotificationProvider } from '@/contexts/notification-context'
import { NotificationToastContainer } from '@/components/notification-toast'
import { AIChatbotProvider } from '@/components/ai-chatbot-provider'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata = {
  title: 'Outreach Mosaic',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable}`} suppressHydrationWarning>{/* suppressHydrationWarning: https://github.com/vercel/next.js/issues/44343 */}
      <body className="font-inter antialiased bg-gray-100 dark:bg-gray-900 text-gray-600 dark:text-gray-400">
        <Theme>
          <AuthProvider>
            <AppProvider>
              <CartProvider>
                <NotificationProvider>
                  <AIChatbotProvider>
                    {children}
                    <NotificationToastContainer />
                  </AIChatbotProvider>
                </NotificationProvider>
              </CartProvider>
            </AppProvider>
          </AuthProvider>
        </Theme>
      </body>
    </html>
  )
}
