-- Seed notification types
INSERT INTO notification_types (id, name, display_name, description, icon, color, is_active, created_at, updated_at) VALUES
('notif_type_1', 'announcement', 'Announcement', 'General announcements and updates', '📢', '#3B82F6', true, NOW(), NOW()),
('notif_type_2', 'system_update', 'System Update', 'System maintenance and updates', '🔧', '#10B981', true, NOW(), NOW()),
('notif_type_3', 'feature_release', 'Feature Release', 'New features and improvements', '🚀', '#8B5CF6', true, NOW(), NOW()),
('notif_type_4', 'security_alert', 'Security Alert', 'Important security notifications', '🔒', '#EF4444', true, NOW(), NOW()),
('notif_type_5', 'maintenance', 'Maintenance', 'Scheduled maintenance windows', '⚙️', '#F59E0B', true, NOW(), NOW());

-- Seed sample notifications
INSERT INTO notifications (id, title, body, image_url, type_id, is_active, is_global, target_user_ids, priority, expires_at, created_at, updated_at, created_by) VALUES
('notif_1', 'Welcome to our new notification system!', 'We''re excited to introduce our new notification system that will keep you updated with important information, system updates, and new features. You can manage your notification preferences in your account settings.', 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=400&h=200&fit=crop', 'notif_type_1', true, true, '{}', 'NORMAL', NULL, NOW() - INTERVAL '2 days', NOW() - INTERVAL '2 days', NULL),
('notif_2', 'System maintenance scheduled for tonight', 'We will be performing scheduled maintenance tonight from 11 PM to 2 AM EST. During this time, some features may be temporarily unavailable. We apologize for any inconvenience.', NULL, 'notif_type_5', true, true, '{}', 'HIGH', NOW() + INTERVAL '1 day', NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day', NULL),
('notif_3', 'New dashboard features are now available', 'Check out the new analytics dashboard with enhanced reporting capabilities, real-time data visualization, and customizable widgets. These features will help you better understand your data and make informed decisions.', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=200&fit=crop', 'notif_type_3', true, true, '{}', 'NORMAL', NULL, NOW() - INTERVAL '3 hours', NOW() - INTERVAL '3 hours', NULL),
('notif_type_4', 'Security update required', 'Please update your password and enable two-factor authentication to ensure your account security. This is a critical security measure to protect your data.', NULL, 'notif_type_4', true, true, '{}', 'URGENT', NOW() + INTERVAL '7 days', NOW() - INTERVAL '6 hours', NOW() - INTERVAL '6 hours', NULL),
('notif_5', 'API rate limits have been updated', 'We''ve updated our API rate limits to provide better performance for all users. The new limits are more generous and should accommodate most use cases. Check our documentation for details.', NULL, 'notif_type_2', true, true, '{}', 'LOW', NULL, NOW() - INTERVAL '1 week', NOW() - INTERVAL '1 week', NULL),
('notif_6', 'Holiday schedule announcement', 'Our support team will have reduced availability during the holiday season (December 24-26). Emergency support will still be available. We wish you happy holidays!', 'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&h=200&fit=crop', 'notif_type_1', true, true, '{}', 'NORMAL', NOW() + INTERVAL '30 days', NOW() - INTERVAL '2 weeks', NOW() - INTERVAL '2 weeks', NULL);
